# Generated by Django 5.2.5 on 2025-09-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tender Name')),
                ('ref_no', models.CharField(max_length=100, unique=True, verbose_name='Reference Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('submission_date', models.DateField(verbose_name='Submission Date')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('ongoing', 'Ongoing')], default='ongoing', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'db_table': 'tenders',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
